### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by r--w** [Blueliv/logstash-input-blueliv#1]
Hi,
For given configuration:

```
input { blueliv { api_url => "https://freeapi.blueliv.com" http_timeout => 1000 api_key => "xxxxxxxxx-6ac9-44d4-b818-c1b59e03657b" feeds => { "botips" => { "active" => false } "crimeservers" => {"active" => true "feed_type" => "all" }}}}
output {
  stdout { codec => rubydebug }
}
```

And command:

```
bin/logstash -f blueliv.conf --debug
```

I get:

```
.....
Resource https://freeapi.blueliv.com/v1/ip/test not found {:level=>:info, :file=>"logstash/inputs/blueliv.rb", :line=>"198", :method=>"get_feed"}
Will retry in 5 seconds {:level=>:info, :file=>"logstash/inputs/blueliv.rb", :line=>"209", :method=>"get_feed"}
....
```

**Comment by BluelivSecurity** [comment]
Hi Radoslaw,

It seems like you're using the blueliv.conf instead of blueliv_free.conf (https://github.com/Blueliv/elk-config-examples/blob/master/logstash/blueliv_free.conf).  
Is it possible? If not, can you please send us an email (community@blueliv.com) and we will investigate this much more closely.

Thank you very much,
Blueliv Engineering Team

**Comment by r--w** [comment]
The file is Just named blueliv.conf but as you can see in the comment above i'm using free version.

**Comment by BluelivSecurity** [comment]
Hi @r--w,

IPs feed is not available in our free API. You can check this and more information about the available resources in our  <a href="https://github.com/Blueliv/api-python-sdk/wiki/Blueliv-REST-API-Documentation#resources-overview" target="_blank">wiki</a>.

Best regards,
Blueliv Engineering Team
